### ISSUE TITLE
[plugin-github] Cannot determine GitHub owner or repository

### ISSUE THREAD

**Issue by gabormagyar** [tophat/monodeploy#514]
**Describe the bug**

I get this error when I run my publish workflow in one of my repositories. (It is unfortunately private.)

```
Executing Release Hooks
  ➤ YN0001: │ Error: Cannot determine GitHub owner or repository
      at PluginInternals (/home/runner/work/fnd-configs/fnd-configs/.yarn/cache/@monodeploy-plugin-github-npm-0.4.1-6d7a11f9d2-2fb1a2ef02.zip/node_modules/@monodeploy/plugin-github/lib/plugin.js:29:15)
```

This same publish workflow works fine in other private repositories, same config and everything.

- [ ] I am interested in contributing a fix.

**To reproduce**

I am unable to reproduce this error locally or in Github Actions on another repo

**Expected behavior**

GitHub plugin publishes a release

**Environment (please complete the following information):**

- OS: GitHub Actions Ubuntu 20.04.4 LTS Runner
- Monodeploy Version: 3.3.0
  - Monodeploy GitHub Plugin Version: 0.6.1
- Yarn Version: 3.2.3
  - Yarn module linker: pnp
- Node Version: 16.16.0
- Git Version: not sure

**Additional context**

Publish workflow:

```yaml
name: Publish

on:
  # Whenever manually triggered
  workflow_dispatch: {}
  # And every Tuesday at 6:30 UTC
  schedule:
    - cron: '30 6 * * TUE'

jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          # Need to fetch history, not just current commit
          fetch-depth: 0
          # This workflow currently needs to use the admin PAT token to bypass branch protection rules on push to main
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 16

      - name: Set up commit author
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'

      - run: yarn
      - run: yarn monodeploy
        env:
          # PAT token needed to publish GitHub releases (contents: write)
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Node auth token needed for .yarnrc.yml to be able to access private MBH packages (packages: write)
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Config:

```js
module.exports = {
  preset: 'monodeploy/preset-recommended',
  changesetIgnorePatterns: ['**/test/**'],
  conventionalChangelogConfig: '@tophat/conventional-changelog-config',
  changelogFilename: '<packageDir>/CHANGELOG.md',
  plugins: ['@monodeploy/plugin-github'],
  git: {
    push: true,
  },

  // This only matters for --dry-run
  forceWriteChangeFiles: true,
}
```
